const {
	username,
	password,
	email,
	displayName,
	cheakUsername,
	cheakPassword,
	cheakEmail,
	token,
	pages,
	id,
	postTitle,
	postBody,
	postId,
	errors,
} = require('./validator');

exports.validator = {
	signup: [username, password, email, displayName, errors],
	login: [cheakUsername, cheakPassword, errors],
	reset: [cheakUsername, cheakEmail, errors],
	update: [token, email, errors],
	token: [token, errors],
	postAll: [pages, errors],
	postId: [id, errors],
	postUserId: [id, pages, errors],
	createPost: [token, postTitle, postBody, errors],
	updatePost: [token, postTitle, postBody, postId, errors],
	deletePost: [token, postId, errors],
};
